# Generated by Django 5.2.3 on 2025-06-22 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='audio/original/')),
                ('converted_file', models.FileField(blank=True, null=True, upload_to='audio/converted/')),
                ('original_emotion', models.CharField(blank=True, choices=[('ANG', 'Anger'), ('DIS', 'Disgust'), ('FEA', 'Fear'), ('HAP', 'Happy'), ('NEU', 'Neutral'), ('SAD', 'Sad')], max_length=3)),
                ('target_emotion', models.CharField(choices=[('ANG', 'Anger'), ('DIS', 'Disgust'), ('FEA', 'Fear'), ('HAP', 'Happy'), ('NEU', 'Neutral'), ('SAD', 'Sad')], max_length=3)),
                ('confidence_scores', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
